ARG BALENA_ARCH=%%BALENA_ARCH%%

FROM balenalib/$BALENA_ARCH-debian
ARG BALENA_ARCH=%%BALENA_ARCH%%

# Get apt-get dependencies.
RUN apt-get update
RUN apt-get -y install python3 python3-setuptools python3-pip python3-pil
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Setup python packages
RUN python3 -m pip install --upgrade pip setuptools
RUN python3 -m pip install requests

WORKDIR /usr/src/app

COPY . ./

RUN chmod +x start.sh

CMD ["bash", "start.sh"]