version: '2'
volumes:
  photos_data:
services:
  kivy:
    restart: always
    build: ./kivy
    privileged: true
    volumes: 
      - "photos_data:/photos"
    ports:
      - 8080:8080
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  photos:
    privileged: true
    restart: always
    build: ./photos
    volumes: 
      - "photos_data:/photos"