version: '2'
volumes:
  photos_data:
services:
  kivy:
    restart: always
    build: ./kivy
    privileged: true
    volumes: 
      - "photos_data:/photos"
    ports:
      - 8080:8080
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  wifi-connect:
    restart: always
    build: ./wifi-connect
    network_mode: "host"
    labels:
        io.balena.features.dbus: '1'
    cap_add:
        - NET_ADMIN
    environment:
        DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
  photos:
    privileged: true
    restart: always
    build: ./photos
    volumes: 
      - "photos_data:/photos"