FROM balenalib/raspberrypi3-debian

RUN [ "cross-build-start" ]

# Get apt-get dependencies.
RUN apt-get update
RUN apt-get -y install apt-utils
RUN apt-get -y install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev
RUN apt-get -y install libgstreamer1.0-dev gstreamer1.0-alsa gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-omx
RUN apt-get -y install python3 cython3 python3-numpy python3-pygame python3-dev ffmpeg libportmidi-dev libsmpeg-dev libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff5-dev libx11-dev libmtdev-dev
RUN apt-get -y install python3-setuptools zlib1g-dev build-essential libgl1-mesa-dev libgles2-mesa-dev
RUN apt-get -y install xvfb pulseaudio xsel
RUN apt-get -y install python3-pip

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip setuptools
RUN python3 -m pip install kivy
RUN python3 -m pip install kivy_examples
RUN python3 -m pip install ffpyplayer

RUN [ "cross-build-end" ]

ENV KIVY_VIDEO ffpyplayer

WORKDIR /usr/src/app

COPY . ./

RUN chmod +x start.sh

CMD ["bash", "start.sh"]